configuration: Debug
before_build:
  - nuget restore
build:
  project: SpiceSharp.sln

os: Visual Studio 2017

assembly_info:
  patch: true
  file: AssemblyInfo.cs
  assembly_version: '{version}'
  assembly_file_version: '{version}'